version: '3.8'

services:
  demoglobal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demoglobal-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_VCS_API_URL=https://vcs.trustos.telefonicatech.com:9443
      - NEXT_PUBLIC_ENV_MODE=prod
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL:-http://localhost:3000/api/auth}
    networks:
      - demoglobal-network

networks:
  demoglobal-network:
    driver: bridge